### ISSUE TITLE
uPath: The engine node is incompatible with this module. Expected ">=4 <=9"

### ISSUE THREAD

**Issue by ahadb** [garmeeh/lerna-starter#8]
Run `yarn install`

```bash
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

[Possible fixes](https://github.com/yarnpkg/yarn/issues/5727) (please see the thread)

- [ ] Update uPath
- [x] Create .yarnrc and add in: `--ignore-engines 

...sent PR for the aforementioned checklist tick 🤓

**Comment by garmeeh** [comment]
Thanks for the PR 😄
